package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.UserDO;

public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Jun 01 22:35:37 CST 2019
     */
    int insert(UserDO record);

    /**
     * 注册用户信息
     * @param record
     * @return
     */

    int insertSelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed May 15 17:05:51 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed May 15 17:05:51 CST 2019
     */



    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed May 15 17:05:51 CST 2019
     */
    int updateByPrimaryKey(UserDO record);


    /**
     * 根据手机号获取用户对象
     * @param telphone
     * @return
     */
    UserDO selectByTelphone(String telphone);

    /**
     * 基于id，查询用户信息
     * @param id
     * @return
     */
    UserDO selectByPrimaryKey(Integer id);



}