package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.UserPasswordDO;

public interface UserPasswordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Jun 01 22:35:37 CST 2019
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Jun 01 22:35:37 CST 2019
     */
    int insert(UserPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Jun 01 22:35:37 CST 2019
     */
    int insertSelective(UserPasswordDO record);

    /**
     * 基于id创查询用户密码
     * @param userId
     * @return
     */

    UserPasswordDO selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Jun 01 22:35:37 CST 2019
     */
    int updateByPrimaryKeySelective(UserPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sat Jun 01 22:35:37 CST 2019
     */
    int updateByPrimaryKey(UserPasswordDO record);

    /**
     * 基于用户id查询用户的密码
     * @param userId
     * @return
     */
    UserPasswordDO selectByUserId(Integer userId);
}